version: 0.1.0-{build}
before_build:
- ps: nuget restore
init:
- ps: Set-WinSystemLocale ru-RU
- ps: Start-Sleep -s 5
- ps: Restart-Computer
install:
- cmd: >-
    mkdir engine

    cd engine

    curl -o os.exe http://oscript.io/downloads/latest/exe

    os.exe /silent

    set PATH=%ProgramFiles(x86)%\OneScript\bin;%PATH%

    cd ..

    oscript -version

    opm install opm

build:
  verbosity: minimal
test_script:
- ps: nunit3-console --x86 NUnitTests\bin\Debug\NUnitTests.dll

after_build:
- cmd: >-
    copy v8unpack\bin\Debug\v8unpack.dll oslib\bin\

    cd oslib

    opm build .

    cd ..

artifacts:
- path: oslib\*.ospx
  name: v8unpack
